- website/cosmos/solar-system/index.mdx
- website/cosmos/solar-system/planets/earth.mdx
- website/cosmos/solar-system/planets/jupiter.mdx
- website/cosmos/solar-system/planets/mars.mdx
- website/cosmos/solar-system/planets/mercury.mdx
- website/cosmos/solar-system/planets/neptune.mdx
- website/cosmos/solar-system/planets/planet-x.mdx
- website/cosmos/solar-system/planets/saturn.mdx
- website/cosmos/solar-system/planets/uranus.mdx
- website/cosmos/solar-system/planets/venus.mdx
- website/docs/the-keyword.mdx
Updated documentation for improved readability and user experience.
> docs: update for better readability

- website/msp/overview.mdx
> This is a test PR

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- website/docs/guides/git.mdx
Thank you for your contribution to the [MKX SpaceHub](https://mkeithx.github.io/) project!
> bumped guides

- website/src/css/custom.css
- website/src/plugins/featureRequests/FeatureRequestsPlugin.js
- website/src/plugins/featureRequests/cannyScript.js
- website/src/plugins/featureRequests/styles.module.css
Thank you for your contribution to the [MKX SpaceHub](https://mkeithx.github.io/) project! Before submitting this pull request, please ensure the following:
> fix featureRequests

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- website/docs/the-keyword.mdx
- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
- website/src/css/custom.css
- website/src/pages/tests.mdx
Thank you for your contribution to the [MKX SpaceHub](https://mkeithx.github.io/) project!
> Update dependencies, css and docs.

- .github/workflows/deploy.yml
- website/docs/configuration.mdx
> test: pages

- website/docs/keyword.mdx
- website/docusaurus.config.ts
- website/msp/snippets/email-scripts.mdx
> docs: fix typos

- .github/workflows/deploy.yml
- website/docs/keyword.mdx
- website/src/pages/index.tsx
> CF pages dev

- website/blog/2024/07-01-devops-july.mdx
- website/docusaurus.config.ts
- website/sidebars.ts
> misc: update prism theme

- website/docs/devops/admin-center/training/email-management.mdx
- website/docs/devops/admin-center/training/install-via-intune.mdx
- website/docs/devops/index.mdx
- website/docusaurus.config.ts
> docs: added intune guides

- website/docs/devops/snippets/email-templates.mdx
- website/docs/devops/snippets/index.mdx
- website/docs/devops/snippets/tech-notes.mdx
- website/sidebars.ts
> docs: update tech-notes in devops

- website/docs/devops/admin-center/training/install-via-intune.mdx
- website/docs/devops/index.mdx
- website/docs/devops/troubleshoot/ms-teams.mdx
- website/docusaurus.config.ts
- website/src/pages/index.tsx
> fix: minor typo errors

- website/docusaurus.config.ts
> feat:update search index

- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
> feat: web analytics

- .github/ISSUE_TEMPLATE/documentation.yml
> _Briefly describe the purpose of this PR._
Added "needs-triage" to bug report
> _List the changes made in this PR._
> _Describe how to test the changes and the expected behavior. Provide steps or links if necessary._
> _Reference any related issues or pull requests._
> misc: Update bug report

- website/community/kitiplex/m365-guidelines.mdx
> _Briefly describe the purpose of this PR._
> _List the changes made in this PR._
> _Describe how to test the changes and the expected behavior. Provide steps or links if necessary._
> _Reference any related issues or pull requests._
> test: Internal PR test

- .github/workflows/deploy.yml
> _Briefly describe the purpose of this PR._
> _List the changes made in this PR._
> _Describe how to test the changes and the expected behavior. Provide steps or links if necessary._
> _Reference any related issues or pull requests._
> fix: LastUpdate

- website/blog/2024/08-19-august-24-specials.mdx
Internal PR to test site behavior via remote repo using [vscode.dev](https://vscode.dev) 
N/A
N/A
[PR#82](https://github.com/mkeithX/mkeithx.github.io/pull/82)
> misc(blog): Update aug specials

- .github/workflows/pages-deployment.yml
- website/package-lock.json
- website/package.json
> _Briefly describe the purpose of this PR._
> _List the changes made in this PR._
> _Describe how to test the changes and the expected behavior. Provide steps or links if necessary._
> _Reference any related issues or pull requests._
> fix: action date not updating

- .github/workflows/pages-deployment.yml
- website/community/kitiplex/team.mdx
- website/docs/custom-deployment/deploy-to-cloudflare-pages.mdx
- website/docs/keyword.mdx
- website/docusaurus.config.ts
- website/sidebars.ts
- website/src/components/TeamProfileCards/index.tsx
This internal PR address minor typo issues and improve landing pages
N/A
N/A
N/A
> docs(fix): minor typos

- .github/PULL_REQUEST_TEMPLATE.md
- website/docs/configs/guides/deployment/deploy-github.mdx
Bumped PR template for clarity.
n/a
n/a
n/a
> misc: Update PR template

- website/docs/keyword.mdx
- website/docusaurus.config.ts
- website/src/pages/index.tsx
This pull request introduces several enhancements aimed at improving the search engine optimization (SEO) for the entire website.
These enhancements will increase the site's visibility in search engines, making it easier for users to find valuable resources.
> misc: SEO Enhancements

- .eslintignore
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .prettierignore
- .prettierrc
- website/.eslintrc
- website/.npmrc
- website/admonitionsConfig.ts
- website/community/kitiplex/cookie-policy.mdx
- website/community/kitiplex/m365-terms-of-use.mdx
- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
- website/redirects.ts
- website/src/pages/tests.mdx
- website/tsconfig.json
This PR focuses on refactoring the existing codebase by splitting large files into smaller, more manageable modules. 
As the codebase grows, maintaining readability and organization becomes increasingly challenging. By modularizing the code, we aim to simplify navigation, improve collaboration among team members, and make future enhancements easier to implement.
N/A
N/A
> refactor: Splitting Code for Improved Readability and Maintenance

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- website/docs/contributing/index.mdx
- website/docs/contributing/reporting-issues.mdx
- website/sidebars.ts
- website/src/css/custom.css
- website/src/pages/index.module.css
- website/src/pages/index.tsx
This internal PR focuses on clearer bug report and feature request templates.
> feat(test): bump community forms

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/workflows/build-deploy.yml
- .github/workflows/dependency-review.yml
- .github/workflows/run-python.yml
- examples/python-starters/hello.py
- website/docs/contributing/index.mdx
- website/package-lock.json
- website/package.json
- website/sidebars.ts
- website/src/css/custom.css
This PR features automation/CI and introduces the Scrum framework through projects.
- Improved Tracking
- Enhanced Collaboration
- Time-Saving
> feat: automation and scrum implementation

- .github/workflows/deploy-preview.yml
> misc: update wf actions for preview

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-production.yml
- website/docs/repo/bmi-in-python.mdx
- website/docs/repo/fibonacci-in-python.mdx
- website/docs/repo/password-generator-python.mdx
- website/sidebars.ts
> docs: added python tutorials

- .github/workflows/deploy-preview.yml
This PR addresses issues with the workflow actions in the deployment environment that have caused inconsistencies and deployment failures.
> fix: resolve workflow actions in deployment environment

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/deploy-preview.yml
- website/blog/2024/reviving-django.mdx
- website/docs/repo/index.mdx
-[Issue #135](https://github.com/mkeithX/mkeithx.github.io/issues/135)
> chore: code cleanup

- .github/ISSUE_TEMPLATE/bug.yml
This PR implements a feature to automatically add newly created issues to a specified GitHub project board.
Improves project management by ensuring all issues are tracked effectively.
> feat: project-issue integration

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-production.yml
This PR introduces a new issue template for reporting documentation-related issues. 
To streamline the process of identifying and addressing documentation gaps or inaccuracies, ensuring a more efficient workflow for contributors. 
N/A
N/A
> feat: documentation issue template

- .github/ISSUE_TEMPLATE/documentation.yml
> fix: minor typo issue in issue templates

- CONTRIBUTING.md
- README.md
- website/community/contributing.mdx
- website/community/report-an-issue.mdx
- website/docs/keyword.mdx
- website/src/components/QuickStartCards/index.tsx
This PR enhances the contribution guidelines to improve clarity and usability for new contributors.
Aim to streamline the onboarding experience and foster community engagement.
- Clarified Submission Process: Added step-by-step instructions for opening issues and pull requests.
- Feature Request Guidance: Included information on using the Canny board and the RFC process for suggesting new features.
- Bug Reporting Improvements: Enhanced instructions on effective bug reporting.
n/a
> docs: update contribution guidelines

- website/package-lock.json
- website/package.json
Update wrangler to from 3.80.3 to 3.80.4
> chore: update dependencies

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-production.yml
> misc: bumped deployment workflows

- .github/workflows/codeql.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-production.yml
- .github/workflows/python-setup.yml
- website/docs/introduction.mdx
- website/docs/keyword.mdx
- website/docs/sdlc.mdx
- website/docusaurus.config.ts
- website/sidebars.ts
This PR updates the workflow actions in our GitHub Actions configuration to improve functionality and maintainability.
- Upgrade actions/checkout to version 4.
- Upgrade actions/setup-node to version 4.
- fix: Adjust the deployment command to correctly use npx wrangler for deploying previews.
- refactor: Add environment variables for Cloudflare API token and account ID for better security.
> chore: update workflow actions

- website/docs/introduction.mdx
- website/docs/keyword.mdx
- website/docusaurus.config.ts
- website/src/css/custom.css
Update introduction with clear and concise definition
> docs: update introduction

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- website/docusaurus.config.ts
- website/src/pages/me/index.tsx
- website/src/pages/me/styles.module.css
This PR addresses Issue [#157](https://github.com/mkeithX/mkeithx.github.io/issues/157)
- Issue [#157](https://github.com/mkeithX/mkeithx.github.io/issues/157)
> fix: issue template

- .github/workflows/codeql.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-production.yml
> chore: bumped code analysis

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-production.yml
- website/docs/introduction.mdx
- website/docs/sdlc.mdx
- website/src/components/HomepageFeatures/index.tsx
This PR aims to improve clarity, fix typos and formatting issues.
> docs: update main documentation

- website/docusaurus.config.ts
- website/sidebars.ts
- website/src/pages/me/index.tsx
- website/src/pages/me/styles.module.css
This PR provide a more accurate "about me" and fix minor css issues.
> docs: update about me section

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
This PR addresses minor formatting and content issues in the bug report template to improve clarity and usability for users submitting bug reports.
- Reviewed the `.yml` structure for proper formatting.
- Ensured all fields are functioning as expected in the issue submission process.
- n/a
> fix: minor issues on bug report template

- website/src/components/TeamProfileCards/index.tsx
This internal PR introduces the new members of the Kitiplex Core team.
> chore: bumped Kitiplex Core team API in /website

- website/babel.config.js
This PR aligns with [Docusaurus v3.6](https://docusaurus.io/blog/releases/3.6#other-changes).
> refactor: remove babel.config.js in /website

- README.md
- website/.npmrc
- website/package-lock.json
- website/package.json
- website/src/css/custom.css
- website/src/pages/index.module.css
- website/wrangler.toml
This PR simplifies the repo's `README`.
- **chore**: No feature changes
> docs: bumped repo README

- website/package-lock.json
- website/package.json
This PR updates the following:
- types/nodes from 22.9.1 to 22.10.1
- cloudflare/workers-types from 4.20241112.0 to 4.20241127.0
- wrangler from 3.88.0 to 3.91.0
- typescript from 5.6.3 to 5.7.2
> chore(deps): update various dependencies in /website

- website/docs/devops/admin-center/emergency-accounts.mdx
- website/docs/introduction.mdx
- website/docusaurus.config.ts
- website/package-lock.json
- website/sidebars.ts
- website/src/css/custom.css
- website/src/pages/index.module.css
This PR reorganizes the navbar to improve clarity and usability.
> refactor(navbar): bumped navbar for better navigation in /website

- website/community/issue/conventional-commits-examples.mdx
- website/community/issue/report.mdx
- website/community/issue/style-guide/_category_.yml
- website/package-lock.json
This PR enhances structure organization for better clarity
N/A
> chore: reorganize structure for clarity in /website

- .github/workflows/python-setup.yml
- notebook.ipynb
- website/blog/2024/august-specials.mdx
- website/blog/2024/welcome.mdx
- website/blog/authors.yml
- website/blog/tags.yml
- website/blog/workplace/remote-desktop/index.mdx
This PR performs a general cleanup and refactoring of the codebase, focusing on improving readability, structure, and maintainability.
> chore: codebase cleanup to improve maintainability

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/dependabot.yml
This PR adds `reviewers` in dependabot config.
- **misc**: Code maintenance, no feature changes
> misc: update-dependabot-attributes

- .github/workflows/ci.yml
> fix: workflow actions

- .github/workflows/ci.yml
- website/docusaurus.config.ts
- website/src/pages/projects/_components/projectCards/index.tsx
> chore: code cleanup in /website

- .github/workflows/ci.yml
- .github/workflows/dependency-review.yml
- .github/workflows/python-setup.yml
- website/docusaurus.config.ts
- website/wrangler.toml
This PR enhances the search APIs
n/a
n/a
> feat: update search apis in /website

- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
This PR introduces docusarus/faster feature
> feat: docusaurus faster

- .github/workflows/ci-test.yml
- .github/workflows/ci.yml
> misc: added workflow actions

- .github/workflows/build-and-deploy.yml
> chore: update actions variables

- .github/workflows/build-and-deploy.yml
- .github/workflows/dependency-review.yml
- .github/workflows/python-setup.yml
- website/docusaurus.config.ts
- website/src/css/custom.css
- website/src/pages/me/index.tsx
This PR focuses on cleaning up the code within our GitHub workflow actions to improve readability, maintainability, and efficiency.
n/a
> refactor(workflows): code cleanup in GitHub workflow actions

- .github/workflows/build-and-deploy.yml
- Fixed concurrency group expression.
- Corrected typo in Cloudflare Pages deploy step.
- Refined deploy condition for main branch push.
> misc: bump workflow actions in /website

- .github/workflows/build-and-deploy.yml
- website/.npmrc
> fix(ci/cd): update concurrency and fix typos in /website

- website/src/pages/foobar/index.tsx
- website/src/pages/foobar/styles.module.css
- website/src/pages/index.module.css
Improve clarity and aesthetics
- [#294](https://github.com/mkeithX/mkeithx.github.io/issues/294)
> chore: update titles and styles for improved clarity and aesthetics

- website/docusaurus.config.ts
- website/redirects.ts
- website/src/css/custom.css
- website/src/pages/index.module.css
- website/src/pages/tests.mdx
- website/src/theme/SearchBar/index.tsx
- website/src/theme/SearchBar/styles.css
This PR enhances search for a better user experience using `docusaurus` swizzle.
> chore: custom algolia search

- website/docusaurus.config.ts
This PR simplifies the site tagline.
> chore: update site tagline

- website/docusaurus.config.ts
This PR fixes the missing SEO metadata by adding necessary meta tags for better search engine indexing and social media sharing. 
- Set correct title and description and added to global metadata config.
> fix: add missing SEO metadata for search visibility

- website/docusaurus.config.ts
This PR closes #305
- removed the `fromExtensions` in config.
- #305
> fix: client side redirects

- website/docusaurus.config.ts
This PR implements theCloudflare analytics feature
> feat: add web-analytics

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature.yml
- website/docusaurus.config.ts
- website/src/theme/SearchBar/index.tsx
Update issue templates and remove test tokens
> chore: update issue template and tokens

- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build-and-deploy.yml
- website/docusaurus.config.ts
Adding login links for Kitiplex dev
N/A
> feat: add dev login

- .github/workflows/build-and-deploy.yml
This PR aims to test wrangler deployment on multiple `env` and bump community health files
n/a
n/a
> tests build and deployment

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/build-and-deploy.yml
- website/docusaurus.config.ts
> test: cloudflare vars and enviroment

- .github/workflows/build-and-deploy.yml
- website/wrangler.toml
> test: remove wrangler toml

- website/docusaurus.config.ts
> misc: update custom fields

- website/docusaurus.config.ts
> misc: update login url

- website/docusaurus.config.ts
> feat: adding google analytics

- website/package-lock.json
- website/package.json
Bumps dotenvx to v1.33.0.
- n/a
- #332
> chore: update @dotenvx/dotenvx in /website

- LICENSE
- README.md
- website/community/kitiplex/team.mdx
- website/docs/cli.mdx
- website/docs/downloads.mdx
- website/docs/introduction.mdx
- website/docusaurus.config.ts
- website/package-lock.json
- website/src/components/TeamProfileCards/index.tsx
- website/src/css/custom.css
- website/src/pages/feeling-lucky/index.tsx
- website/src/pages/index.tsx
- website/src/pages/tests.mdx
- website/src/theme/SearchBar/index.tsx
This PR improves the `README.md` file by enhancing clarity, fixing grammatical errors, and providing detailed contribution guidelines.
> docs(core): update readme

- website/docs/downloads.mdx
- website/src/components/HomepageFeatures/index.tsx
- website/src/components/HomepageFeatures/styles.module.css
- website/src/css/custom.css
- website/src/pages/index.module.css
This PR focuses on cleaning up CSS  by removing unused and redundant styles.
> chore: css cleanup in /website

- website/docusaurus.config.ts
- website/src/css/custom.css
- website/src/pages/tests.mdx
This PR addresses styles issue in custom admonition
> fix: admonitions

- website/docs/aka-ms.mdx
- website/docs/cli.mdx
- website/docusaurus.config.ts
- website/sidebars.ts
- website/sidebarsCommunity.ts
- website/src/pages/tests.mdx
This PR refactors the sidebar structure by:
- Removing redundant sections and comments.
- Streamlining categories and items for a cleaner structure.
- Standardizing naming conventions for improved clarity.
> refactor(sidebars): refine sidebar structure

- .github/workflows/build-and-deploy.yml
- website/package-lock.json
- website/package.json
This PR updates packages/dependencies in `website`.
- **chore**: Code maintenance, no feature changes 
- #362
- #363
> chore: update dependencies in /website

- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
- website/social.ts
- website/src/components/ComingSoon/index.tsx
- website/src/components/HomepageFeatures/index.tsx
- website/src/pages/cosmos/index.tsx
- website/src/pages/cosmos/styles.module.css
- website/src/pages/index.tsx
- website/static/img/undraw_towing.svg
This PR updates the dependencies to address security vulnerabilities identified in the existing packages.
> chore(deps): update dependencies to fix vulnerabilities

- examples/python-starters/04-password-generator/main.py
Replaced usage of `random.choice()` with `secrets.choice()` in the password generation logic to improve security. The `secrets` module provides cryptographically secure random numbers, making it more suitable for generating passwords compared to `random`, which is not designed for cryptographic use.
- Replaced `random.choice()` with `secrets.choice()` in the `generate_password()` function.
- Ensured secure randomness for password generation at all complexity levels (weak, medium, strong).
> chore(security): replace `random` module with `secrets`

- .github/workflows/python-setup.yml
- examples/python-script-template/main.py
- examples/python-script-template/tests/test_main.py
This PR fixes issues with running `pytest` in the python-script-template in /examples.
> fix(api): pytest in python-script-template

- examples/python-starters/05-video-downloader/main.py
- examples/python-starters/11-currency-converter/main.py
This PR adds a new (python) application, `currency-converter`, to the /examples dir.
> feat: add new currency-converter app

- website/docs/system-administration/ms-entraid-conditional-access.mdx
This PR introduces docs/articles for best practices related to conditional access policies in Entra. 
- N/A
> docs: intro to conditional access policy

- website/docusaurus.config.ts
This PR focuses on updating gtag configuration and fix minor issues on some variables
> fix:gtag-configuration

- website/docs/downloads.mdx
- website/docs/system-administration/ms-intune/custom-lockscreen.mdx
- website/docs/system-administration/ms-intune/deploy-win32-app.mdx
- website/docusaurus.config.ts
- website/package-lock.json
This PR focuses on links updates, improve clarity in the existing articles and introduces initial docs for deploying Win32 applications in Microsoft Intune.
- n/a
> docs: system admin articles

- website/docs/configs/index.mdx
- website/docs/system-administration/ms-intune/custom-lockscreen.mdx
- website/docusaurus.config.ts
This PR addresses minor issues in search functionality.
- n/a
> fix: minor issues in search index

- website/src/components/TeamProfileCards/index.tsx
My initial contribution to the SpaceHub project.
> docs: intial contribution

- website/src/components/TeamProfileCards/index.tsx
This PR marks my initial commit for the SpaceHub project.
> docs: initial commit

- website/docs/system-administration/02-cli.mdx
> docs: update guides

- .github/workflows/build-and-deploy.yml
This PR updates the 'CI/CD' workflow and some docs.
> misc: update GitHub actions and some docs

- .github/workflows/build-and-deploy.yml
This PR update CI/CD pipeline for GitHub Pages and Cloudflare deployment
- **Refactored** the CI/CD pipeline to improve deployment steps for both GitHub Pages and Cloudflare.
- **Added** concurrency control to prevent multiple builds from running simultaneously for the same workflow.
- **Updated** the `node-version` setup to always use the latest LTS (`lts/*`) in the `setup-node` step.
- **Optimized** the `publish` job to handle deployment conditions more efficiently, ensuring deployment only happens on `push` to `main` or when `pull_request` events occur.
- **Enhanced** the permissions for actions to ensure necessary access for deployments and pages.
- n/a
> misc: update actions workflow

- website/package-lock.json
This PR updates the dependencies for improved stability and performance.
- N/A
> chore(deps): update package in /website
